### ISSUE TITLE
학습 기간 999일

### ISSUE THREAD

**Issue by danielk5432** [cotwo0139/FuckEBSLecture#5]
콘솔에 코드를 붙여넣기 하고 다시 나오면 학습 기간이 999일로 나옵니다.
![image](https://user-images.githubusercontent.com/41940585/78949844-d8c50700-7b07-11ea-9a52-53ede37868e4.png)

**Comment by cotwo0139** [comment]
비정상적인 시간 값을 넘겨서 그러는것 같습니다.
