### ISSUE TITLE
완료가 안되요

### ISSUE THREAD

**Issue by reload02** [cotwo0139/FuckEBSLecture#6]
atnlcNo: 563268
lctreSeCode: undefined
stepSn: 171732
cntntsTyCode: undefined
revivTime: undefined
--------------------------------------
0 Steps
Starting LctreSn (NaN)
End LctreSn (NaN)

이렇게 뜨는데 어떻게 해야되나요?

**Comment by cotwo0139** [comment]
영상으로 되어있는 강의만 가능할겁니다

**Comment by cotwo0139** [comment]
강의 타입이 영상인지 확인해주세요

**Comment by cotwo0139** [comment]
강의 번호가 1씩 올라가는 구조가 아닌 고유한 ID여서 발생한 문제입니다. 메인 파일의 한에 수정되었습니다. 관련 PR #9
