### ISSUE TITLE
강의 번호 지정해서 처리도 가능한가요?

### ISSUE THREAD

**Issue by tjtdkr** [cotwo0139/FuckEBSLecture#7]
1~50번까지 있다고 하면 1~3번까지만 되게 할 수 있는 방법이 있나 궁금합니다

**Comment by Zero-Brazil734** [comment]
이미 본인이 실수로 끝까지 봐버려서 목록에서 엄청 튄다고 말한 이상... 언젠가는 가능하도록 변경하실거 같습니다

**Comment by cotwo0139** [comment]
현재 PR #9 로 인해 현재 강의, 모든 강의 설정 가능하게 메인 JS파일은 변경되었습니다.
